import fs from 'node:fs/promises';
import path from 'node:path';

const RELEASE_URL = 'https://github.com/danielrna/enterprise-modernization-platform-public/releases/tag/v0.1.0';
const SAMPLE_REPORT_URL = 'https://github.com/danielrna/enterprise-modernization-platform-public/releases/download/v0.1.0/emp-smoke-report.zip';
const DOCKER_IMAGE = 'danielrna/enterprise-modernization-platform:v0.1.0';
const GITHUB_ACTION = 'danielrna/enterprise-modernization-platform-public@v0.1.0';

export async function generateMigrationHub({ outDir, benchmarks = [], benchmarksDir = path.resolve(outDir, '..', 'benchmarks') }) {
  await fs.mkdir(outDir, { recursive: true });
  const benchmarkEvidence = await loadBenchmarkReports(benchmarksDir);
  const migrationBenchmarks = benchmarkEvidence.length ? benchmarkEvidence : normalizeBenchmarks(benchmarks);
  await fs.writeFile(path.join(outDir, 'index.html'), renderHubIndex(migrationBenchmarks));
  await fs.writeFile(path.join(outDir, 'spring-boot-2-to-3.html'), renderMigrationPage(migrationBenchmarks));
}

export async function generateBenchmarkIndex({ outDir, reports }) {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'index.html'), renderBenchmarkIndex(reports));
}

function renderHubIndex(benchmarks) {
  const rows = benchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.pack)}</td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${escapeHtml(formatReadiness(benchmark.readiness))}</td></tr>`).join('');
  return page('Migration Hub', `
    <section>
      <h1>Migration Hub</h1>
      <p>Guides, reports, examples, and benchmark evidence for mandatory enterprise modernization work.</p>
    </section>
    <section class="layout">
      <a class="tile" href="spring-boot-2-to-3.html"><strong>Spring Boot 2 to 3</strong><span>Readiness guide, risks, report shape, and benchmark catalog.</span></a>
      <a class="tile" href="../benchmarks/index.html"><strong>Benchmark Reports</strong><span>${benchmarks.length} public benchmark reports generated by the CLI.</span></a>
    </section>
    <h2>Benchmark Set</h2>
    <table><thead><tr><th>Project</th><th>Repository</th><th>Pack</th><th>Spring Boot</th><th>Readiness</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function renderMigrationPage(benchmarks) {
  const springBootBenchmarks = benchmarks.filter((benchmark) => benchmark.pack === 'spring-boot-3-readiness');
  const benchmarkRows = springBootBenchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${escapeHtml(formatReadiness(benchmark.readiness))}</td><td>${escapeHtml(benchmark.findings.total)}</td><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/report.json">JSON</a></td></tr>`).join('');

  return page('Spring Boot 2 to 3 Migration', `
    <section>
      <h1>Spring Boot 2 to 3 Migration</h1>
      <p>Readiness evidence for teams preparing the mandatory move from Spring Boot 2.x to Spring Boot 3.x.</p>
    </section>

    <section class="layout">
      <a class="tile" href="${RELEASE_URL}"><strong>Release v0.1.0</strong><span>CLI, Docker image, GitHub Action, MCP, reports, and benchmark evidence.</span></a>
      <a class="tile" href="${SAMPLE_REPORT_URL}"><strong>Sample Report</strong><span>Download the smoke-test HTML and JSON report generated by the public action.</span></a>
    </section>

    <h2>Try in 5 Minutes</h2>
    <p>Run a readiness report on any Java or Spring repository. The output is a static HTML report and a machine-readable JSON report.</p>
    <pre><code>docker run --rm -v "$PWD:/workspace" ${DOCKER_IMAGE} analyze . --pack spring-boot-3-readiness --out reports/spring-boot-readiness</code></pre>
    <p>Open the generated report:</p>
    <pre><code>reports/spring-boot-readiness/index.html</code></pre>

    <h2>GitHub Action</h2>
    <pre><code>name: Spring Boot Readiness

on:
  workflow_dispatch:
  pull_request:

jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run readiness analysis
        uses: ${GITHUB_ACTION}
        with:
          path: .
          pack: spring-boot-3-readiness
          out: emp-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: emp-readiness-report
          path: emp-report</code></pre>

    <h2>Guide</h2>
    <p>This guide focuses on readiness evidence: build metadata, Spring Boot version detection, Jakarta namespace risk, static source findings, and an HTML report that can be shared without a backend.</p>

    <h2>Readiness Signals</h2>
    <ul>
      <li>Explicit Maven or Gradle build metadata</li>
      <li>Spring Boot version discovery</li>
      <li>javax to jakarta migration risk</li>
      <li>Dependency injection and legacy API cleanup findings</li>
      <li>OpenRewrite dry-run readiness for the transformation flow</li>
    </ul>

    <h2>Risk Matrix</h2>
    <table>
      <thead><tr><th>Risk</th><th>Why It Matters</th><th>Evidence Produced</th></tr></thead>
      <tbody>
        <tr><td>Jakarta namespace</td><td>Spring Boot 3 requires Jakarta EE APIs instead of Java EE packages.</td><td>javax usage findings, package-level risk, migration recommendation.</td></tr>
        <tr><td>Spring Boot version drift</td><td>Unknown or unsupported build metadata makes migration scope hard to estimate.</td><td>Maven or Gradle detection, Spring Boot version, applicability status.</td></tr>
        <tr><td>Dependency injection patterns</td><td>Field injection and legacy patterns often surface during framework upgrades.</td><td>Static findings separated by production and test sources.</td></tr>
        <tr><td>Build and test confidence</td><td>A migration is not credible without repeatable validation evidence.</td><td>Compile, test, rollback, and confidence sections when transform validation runs.</td></tr>
        <tr><td>Enterprise rules</td><td>Each organization has internal modernization rules beyond generic framework checks.</td><td>.preflight-rules.yml violations included in scoring and reports.</td></tr>
      </tbody>
    </table>

    <h2>Benchmark Reports</h2>
    <p>These public benchmark reports are checked into the repository and can be served directly from GitHub Pages.</p>
    <table><thead><tr><th>Project</th><th>Repository</th><th>Detected Spring Boot</th><th>Readiness</th><th>Findings</th><th>Data</th></tr></thead><tbody>${benchmarkRows}</tbody></table>

    <h2>What This Does Not Do</h2>
    <ul>
      <li>It does not run a hosted SaaS backend.</li>
      <li>It does not parse Java with a custom compiler or AST.</li>
      <li>It does not replace project-specific migration review.</li>
      <li>It does not apply changes during readiness analysis.</li>
    </ul>

    <h2>FAQ</h2>
    <p><strong>Does readiness analysis apply migrations?</strong> No. It measures readiness and creates evidence. Apply, rollback, compile, and test validation are part of the transformation flow.</p>
    <p><strong>Can this run in CI?</strong> Yes. Use the Docker image directly or the GitHub Action. The output directory can be uploaded as a build artifact.</p>
    <p><strong>Does it require a server?</strong> No. Reports, benchmark pages, and this hub are static files.</p>
  `);
}

function renderBenchmarkIndex(reports) {
  const rows = reports.map((report) => `<tr><td><a href="${escapeHtml(report.slug)}/index.html">${escapeHtml(report.name)}</a></td><td>${escapeHtml(formatReadiness(report.readiness))}</td><td>${escapeHtml(report.source || 'catalog')}</td><td><a href="${escapeHtml(report.repository)}">${escapeHtml(report.repository)}</a></td></tr>`).join('');
  return page('Benchmark Reports', `
    <section>
      <h1>Benchmark Reports</h1>
      <p>Benchmark reports generated from catalog metadata or real repository checkouts.</p>
    </section>
    <table><thead><tr><th>Project</th><th>Readiness</th><th>Source</th><th>Repository</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function formatReadiness(readiness) {
  return readiness === null ? 'N/A' : `${readiness}%`;
}

function page(title, body) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --ink:#17202a; --muted:#64748b; --line:#d8dee8; --bg:#f7f9fb; --panel:#fff; --accent:#1769aa; }
    * { box-sizing:border-box; }
    body { margin:0; font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; color:var(--ink); background:var(--bg); }
    main { max-width:1080px; margin:0 auto; padding:32px 24px; }
    h1 { margin:0 0 8px; font-size:34px; letter-spacing:0; }
    h2 { margin:28px 0 10px; font-size:21px; letter-spacing:0; }
    p { max-width:760px; color:var(--muted); }
    a { color:var(--accent); text-decoration:none; }
    a:hover { text-decoration:underline; }
    .layout { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:14px; margin:24px 0; }
    .tile { display:flex; flex-direction:column; gap:6px; min-height:118px; padding:18px; background:var(--panel); border:1px solid var(--line); border-radius:8px; color:var(--ink); }
    .tile span { color:var(--muted); }
    pre { overflow:auto; padding:14px; background:#111827; color:#f8fafc; border-radius:8px; }
    code { font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
    table { width:100%; border-collapse:collapse; background:var(--panel); border:1px solid var(--line); border-radius:8px; overflow:hidden; }
    th,td { text-align:left; padding:10px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
    th { font-size:12px; color:var(--muted); text-transform:uppercase; }
    li { margin:6px 0; }
    @media (max-width: 720px) { .layout { grid-template-columns:1fr; } h1 { font-size:27px; } }
  </style>
</head>
<body><main>${body}</main></body>
</html>
`;
}

function shortRepository(repository) {
  return repository.replace('https://github.com/', '');
}

async function loadBenchmarkReports(benchmarksDir) {
  const entries = await fs.readdir(benchmarksDir, { withFileTypes: true }).catch(() => []);
  const reports = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const slug = entry.name;
    const reportPath = path.join(benchmarksDir, slug, 'report.json');
    const report = await readJson(reportPath);
    if (!report) continue;
    reports.push(normalizeReport(slug, report));
  }
  return reports.sort(compareBenchmarks);
}

async function readJson(file) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch {
    return null;
  }
}

function normalizeBenchmarks(benchmarks) {
  return benchmarks.map((benchmark) => ({
    slug: benchmark.slug,
    name: benchmark.name,
    repository: benchmark.repository,
    pack: benchmark.pack,
    springBootVersion: benchmark.springBootVersion,
    readiness: benchmark.readiness ?? null,
    findings: {
      total: benchmark.findings?.length ?? 0,
      critical: benchmark.findings?.filter((finding) => finding.severity === 'critical').length ?? 0,
      warning: benchmark.findings?.filter((finding) => finding.severity === 'warning').length ?? 0,
      info: benchmark.findings?.filter((finding) => finding.severity === 'info').length ?? 0
    }
  })).sort(compareBenchmarks);
}

function normalizeReport(slug, report) {
  return {
    slug,
    name: report.project?.name || slug,
    repository: report.project?.source?.startsWith('https://github.com/')
      ? report.project.source
      : `https://github.com/${slug}`,
    pack: report.pack || 'unknown',
    springBootVersion: report.project?.springBootVersion || report.dependencies?.springBootVersion || 'unknown',
    readiness: report.readiness?.overall ?? null,
    findings: {
      total: report.findings?.length ?? 0,
      critical: report.readiness?.counts?.critical ?? 0,
      warning: report.readiness?.counts?.warning ?? 0,
      info: report.readiness?.counts?.info ?? 0
    }
  };
}

function compareBenchmarks(left, right) {
  if (left.pack !== right.pack) return left.pack.localeCompare(right.pack);
  return left.name.localeCompare(right.name);
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}
