import fs from 'node:fs/promises';
import path from 'node:path';

const RELEASE_URL = 'https://github.com/danielrna/enterprise-modernization-platform-public/releases/tag/v0.1.0';
const SAMPLE_REPORT_URL = 'https://github.com/danielrna/enterprise-modernization-platform-public/releases/download/v0.1.0/emp-smoke-report.zip';
const DOCKER_IMAGE = 'danielrna/enterprise-modernization-platform:v0.1.0';
const GITHUB_ACTION = 'danielrna/enterprise-modernization-platform-public@v0.1.0';

export async function generateMigrationHub({ outDir, benchmarks = [], benchmarksDir = path.resolve(outDir, '..', 'benchmarks') }) {
  await fs.mkdir(outDir, { recursive: true });
  const benchmarkEvidence = await loadBenchmarkReports(benchmarksDir);
  const migrationBenchmarks = benchmarkEvidence.length ? benchmarkEvidence : normalizeBenchmarks(benchmarks);
  await fs.writeFile(path.join(outDir, 'index.html'), normalizeHtml(renderHubIndex(migrationBenchmarks)));
  await fs.writeFile(path.join(outDir, 'spring-boot-2-to-3.html'), normalizeHtml(renderMigrationPage(migrationBenchmarks)));
}

export async function generateBenchmarkIndex({ outDir, reports }) {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'index.html'), normalizeHtml(renderBenchmarkIndex(reports)));
}

function renderHubIndex(benchmarks) {
  const rows = benchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.pack)}</td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${escapeHtml(formatReadiness(benchmark.readiness))}</td><td>${escapeHtml(benchmark.source)}</td><td>${escapeHtml(benchmark.validation.status)}</td></tr>`).join('');
  return page('Migration Hub', `
    <section>
      <h1>Migration Hub</h1>
      <p>Guides, reports, examples, and benchmark evidence for mandatory enterprise modernization work.</p>
    </section>
    <section class="layout">
      <a class="tile" href="spring-boot-2-to-3.html"><strong>Spring Boot 2 to 3</strong><span>Readiness guide, risks, report shape, and benchmark catalog.</span></a>
      <a class="tile" href="../benchmarks/index.html"><strong>Benchmark Reports</strong><span>${benchmarks.length} public benchmark reports generated by the CLI.</span></a>
      <a class="tile" href="../editions.html"><strong>Editions</strong><span>Community, Professional, Consultant, and Organization options.</span></a>
      <a class="tile" href="../contact.html"><strong>Contact</strong><span>Request Professional, Consultant, or Organization access.</span></a>
    </section>
    <h2>Benchmark Set</h2>
    <table><thead><tr><th>Project</th><th>Repository</th><th>Pack</th><th>Spring Boot</th><th>Readiness</th><th>Source</th><th>Validation</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function renderMigrationPage(benchmarks) {
  const springBootBenchmarks = benchmarks.filter((benchmark) => benchmark.pack === 'spring-boot-3-readiness');
  const validatedBenchmarks = springBootBenchmarks.filter((benchmark) => benchmark.validation?.status === 'passed');
  const validatedBlock = renderValidatedBenchmarks(validatedBenchmarks);
  const benchmarkRows = springBootBenchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${escapeHtml(formatReadiness(benchmark.readiness))}</td><td>${escapeHtml(benchmark.findings.total)}</td><td>${escapeHtml(benchmark.source)}</td><td>${escapeHtml(benchmark.validation.status)}</td><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/report.json">JSON</a></td></tr>`).join('');

  return page('Spring Boot 2 to 3 Migration', `
    <section>
      <h1>Spring Boot 2 to 3 Migration</h1>
      <p>Readiness evidence for teams preparing the mandatory move from Spring Boot 2.x to Spring Boot 3.x.</p>
    </section>

    <section class="layout">
      <a class="tile" href="${RELEASE_URL}"><strong>Release v0.1.0</strong><span>CLI, Docker image, GitHub Action, MCP, reports, and benchmark evidence.</span></a>
      <a class="tile" href="${SAMPLE_REPORT_URL}"><strong>Sample Report</strong><span>Download the smoke-test HTML and JSON report generated by the public action.</span></a>
    </section>

    ${validatedBlock}

    <h2>Consultant Workflow</h2>
    <section class="steps">
      <div><strong>1. Run</strong><span>Execute the free readiness report on the client repository.</span></div>
      <div><strong>2. Send report</strong><span>Share the static HTML report as neutral migration evidence.</span></div>
      <div><strong>3. Fix risks</strong><span>Prioritize Jakarta, build metadata, injection patterns, and client rules.</span></div>
      <div><strong>4. Validate</strong><span>Capture compile and test evidence before proposing migration execution.</span></div>
      <div><strong>5. Sell confidence</strong><span>Position the work as risk reduction, not as a generic code migration.</span></div>
    </section>

    <h2>What You Can Promise a Client</h2>
    <section class="promise">
      <div><strong>Readiness score</strong><span>A clear percentage and category scores for planning.</span></div>
      <div><strong>Version evidence</strong><span>Detected Spring Boot, Java, and build metadata.</span></div>
      <div><strong>Risk inventory</strong><span>Jakarta, static source findings, and repeated risk patterns.</span></div>
      <div><strong>Validation evidence</strong><span>Compile and test status when a checkout can be validated.</span></div>
      <div><strong>Client-owned rules</strong><span>Optional .preflight-rules.yml checks for internal standards.</span></div>
      <div><strong>Shareable report</strong><span>Static HTML and JSON outputs, no backend required.</span></div>
    </section>

    <h2>Free vs Professional</h2>
    <table>
      <thead><tr><th>Edition</th><th>Best For</th><th>Includes</th></tr></thead>
      <tbody>
        <tr><td>Community</td><td>First client conversation</td><td>Readiness analysis, HTML report, JSON report, public benchmark reference.</td></tr>
        <tr><td>Professional</td><td>Paid migration preparation</td><td>Validation evidence, Trust Engine report, repeatable benchmark pack, stronger confidence trail.</td></tr>
        <tr><td>Consultant</td><td>Repeated client work</td><td>Unlimited client usage, enterprise rules workflow, reusable reporting assets.</td></tr>
      </tbody>
    </table>

    <h2>Start With the Free Report</h2>
    <section class="actions">
      <a href="#try-in-5-minutes">Run the free readiness report</a>
      <a href="../benchmarks/gs-spring-boot-27/index.html">Use the validated benchmark as reference</a>
      <a href="../editions.html">Compare editions</a>
      <a href="../contact.html">Request access</a>
      <a href="${RELEASE_URL}">Download v0.1.0</a>
    </section>

    <h2 id="try-in-5-minutes">Try in 5 Minutes</h2>
    <p>Run a readiness report on any Java or Spring repository. The output is a static HTML report and a machine-readable JSON report.</p>
    <pre><code>docker run --rm -v "$PWD:/workspace" ${DOCKER_IMAGE} analyze . --pack spring-boot-3-readiness --out reports/spring-boot-readiness</code></pre>
    <p>Open the generated report:</p>
    <pre><code>reports/spring-boot-readiness/index.html</code></pre>

    <h2>GitHub Action</h2>
    <pre><code>name: Spring Boot Readiness

on:
  workflow_dispatch:
  pull_request:

jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run readiness analysis
        uses: ${GITHUB_ACTION}
        with:
          path: .
          pack: spring-boot-3-readiness
          out: emp-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: emp-readiness-report
          path: emp-report</code></pre>

    <h2>Guide</h2>
    <p>This guide focuses on readiness evidence: build metadata, Spring Boot version detection, Jakarta namespace risk, static source findings, and an HTML report that can be shared without a backend.</p>

    <h2>Readiness Signals</h2>
    <ul>
      <li>Explicit Maven or Gradle build metadata</li>
      <li>Spring Boot version discovery</li>
      <li>javax to jakarta migration risk</li>
      <li>Dependency injection and legacy API cleanup findings</li>
      <li>OpenRewrite dry-run readiness for the transformation flow</li>
    </ul>

    <h2>Risk Matrix</h2>
    <table>
      <thead><tr><th>Risk</th><th>Why It Matters</th><th>Evidence Produced</th></tr></thead>
      <tbody>
        <tr><td>Jakarta namespace</td><td>Spring Boot 3 requires Jakarta EE APIs instead of Java EE packages.</td><td>javax usage findings, package-level risk, migration recommendation.</td></tr>
        <tr><td>Spring Boot version drift</td><td>Unknown or unsupported build metadata makes migration scope hard to estimate.</td><td>Maven or Gradle detection, Spring Boot version, applicability status.</td></tr>
        <tr><td>Dependency injection patterns</td><td>Field injection and legacy patterns often surface during framework upgrades.</td><td>Static findings separated by production and test sources.</td></tr>
        <tr><td>Build and test confidence</td><td>A migration is not credible without repeatable validation evidence.</td><td>Compile, test, rollback, and confidence sections when transform validation runs.</td></tr>
        <tr><td>Enterprise rules</td><td>Each organization has internal modernization rules beyond generic framework checks.</td><td>.preflight-rules.yml violations included in scoring and reports.</td></tr>
      </tbody>
    </table>

    <h2>Benchmark Reports</h2>
    <p>These public benchmark reports are checked into the repository and can be served directly from GitHub Pages. Source shows whether a report came from deterministic catalog metadata or a real repository checkout.</p>
    <table><thead><tr><th>Project</th><th>Repository</th><th>Detected Spring Boot</th><th>Readiness</th><th>Findings</th><th>Source</th><th>Validation</th><th>Data</th></tr></thead><tbody>${benchmarkRows}</tbody></table>

    <h2>What This Does Not Do</h2>
    <ul>
      <li>It does not run a hosted SaaS backend.</li>
      <li>It does not parse Java with a custom compiler or AST.</li>
      <li>It does not replace project-specific migration review.</li>
      <li>It does not apply changes during readiness analysis.</li>
    </ul>

    <h2>FAQ</h2>
    <p><strong>Does readiness analysis apply migrations?</strong> No. It measures readiness and creates evidence. Apply, rollback, compile, and test validation are part of the transformation flow.</p>
    <p><strong>Can this run in CI?</strong> Yes. Use the Docker image directly or the GitHub Action. The output directory can be uploaded as a build artifact.</p>
    <p><strong>Does it require a server?</strong> No. Reports, benchmark pages, and this hub are static files.</p>
  `);
}

function renderValidatedBenchmarks(benchmarks) {
  if (!benchmarks.length) return '';
  const cards = benchmarks.map((benchmark) => `
      <div class="proof-card">
        <strong><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></strong>
        <span>${escapeHtml(shortRepository(benchmark.repository))}</span>
        <div class="mini-metrics">
          <small>${escapeHtml(benchmark.springBootVersion)} Spring Boot</small>
          <small>${escapeHtml(formatReadiness(benchmark.readiness))} readiness</small>
          <small>${escapeHtml(benchmark.validation.confidence)}% confidence</small>
        </div>
      </div>`).join('');
  return `
    <h2>Validated Benchmarks</h2>
    <section class="proof">
      <div>
        <strong>${escapeHtml(benchmarks.length)} checkout-backed benchmark${benchmarks.length === 1 ? '' : 's'} passed compile and test validation.</strong>
        <p>Each green benchmark is generated from a real repository checkout with captured compilation and test evidence.</p>
      </div>
      <div class="metrics">
        <span><strong>${escapeHtml(benchmarks.length)}</strong><small>Validated</small></span>
        <span><strong>passed</strong><small>Compile + tests</small></span>
        <span><strong>${escapeHtml(Math.round(benchmarks.reduce((sum, item) => sum + Number(item.validation.confidence || 0), 0) / benchmarks.length))}%</strong><small>Avg confidence</small></span>
      </div>
    </section>
    <section class="validated">${cards}</section>
  `;
}

function renderBenchmarkIndex(reports) {
  const rows = reports.map((report) => `<tr><td><a href="${escapeHtml(report.slug)}/index.html">${escapeHtml(report.name)}</a></td><td>${escapeHtml(formatReadiness(report.readiness))}</td><td>${escapeHtml(report.source || 'catalog')}</td><td>${escapeHtml(report.validation?.status || 'not_requested')}</td><td><a href="${escapeHtml(report.repository)}">${escapeHtml(report.repository)}</a></td></tr>`).join('');
  return page('Benchmark Reports', `
    <section>
      <h1>Benchmark Reports</h1>
      <p>Benchmark reports generated from catalog metadata or real repository checkouts.</p>
    </section>
    <table><thead><tr><th>Project</th><th>Readiness</th><th>Source</th><th>Validation</th><th>Repository</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function formatReadiness(readiness) {
  return readiness === null ? 'N/A' : `${readiness}%`;
}

function page(title, body) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --ink:#17202a; --muted:#64748b; --line:#d8dee8; --bg:#f7f9fb; --panel:#fff; --accent:#1769aa; }
    * { box-sizing:border-box; }
    body { margin:0; font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; color:var(--ink); background:var(--bg); }
    main { max-width:1080px; margin:0 auto; padding:32px 24px; }
    h1 { margin:0 0 8px; font-size:34px; letter-spacing:0; }
    h2 { margin:28px 0 10px; font-size:21px; letter-spacing:0; }
    p { max-width:760px; color:var(--muted); }
    a { color:var(--accent); text-decoration:none; }
    a:hover { text-decoration:underline; }
    .layout { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:14px; margin:24px 0; }
    .tile { display:flex; flex-direction:column; gap:6px; min-height:118px; padding:18px; background:var(--panel); border:1px solid var(--line); border-radius:8px; color:var(--ink); }
    .tile span { color:var(--muted); }
    .proof { display:grid; grid-template-columns:minmax(0, 1fr) auto; gap:18px; align-items:center; padding:18px; background:var(--panel); border:1px solid var(--line); border-left:4px solid #217a45; border-radius:8px; }
    .proof p { margin:6px 0 0; }
    .metrics { display:grid; grid-template-columns:repeat(3, minmax(92px, 1fr)); gap:10px; }
    .metrics span { display:flex; flex-direction:column; gap:2px; padding:10px 12px; background:#f8fafc; border:1px solid var(--line); border-radius:6px; }
    .metrics small { color:var(--muted); font-size:12px; }
    .validated { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:10px; margin:12px 0 24px; }
    .proof-card { display:flex; flex-direction:column; gap:6px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .proof-card span,.mini-metrics small { color:var(--muted); }
    .mini-metrics { display:flex; flex-wrap:wrap; gap:8px; }
    .steps { display:grid; grid-template-columns:repeat(5, minmax(0, 1fr)); gap:10px; }
    .steps div,.promise div { display:flex; flex-direction:column; gap:5px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .steps span,.promise span { color:var(--muted); }
    .promise { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:10px; }
    .actions { display:flex; flex-wrap:wrap; gap:10px; }
    .actions a { display:inline-flex; align-items:center; min-height:40px; padding:8px 12px; background:var(--panel); border:1px solid var(--line); border-radius:6px; }
    pre { overflow:auto; padding:14px; background:#111827; color:#f8fafc; border-radius:8px; }
    code { font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
    table { width:100%; border-collapse:collapse; background:var(--panel); border:1px solid var(--line); border-radius:8px; overflow:hidden; }
    th,td { text-align:left; padding:10px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
    th { font-size:12px; color:var(--muted); text-transform:uppercase; }
    li { margin:6px 0; }
    @media (max-width: 900px) { .steps,.promise,.validated { grid-template-columns:1fr 1fr; } }
    @media (max-width: 720px) { .layout,.proof,.steps,.promise,.validated { grid-template-columns:1fr; } .metrics { grid-template-columns:1fr; } h1 { font-size:27px; } }
  </style>
</head>
<body><main>${body}</main></body>
</html>
`;
}

function shortRepository(repository) {
  return repository.replace('https://github.com/', '');
}

async function loadBenchmarkReports(benchmarksDir) {
  const entries = await fs.readdir(benchmarksDir, { withFileTypes: true }).catch(() => []);
  const reports = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const slug = entry.name;
    const reportPath = path.join(benchmarksDir, slug, 'report.json');
    const report = await readJson(reportPath);
    if (!report) continue;
    reports.push(normalizeReport(slug, report));
  }
  return reports.sort(compareBenchmarks);
}

async function readJson(file) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch {
    return null;
  }
}

function normalizeBenchmarks(benchmarks) {
  return benchmarks.map((benchmark) => ({
    slug: benchmark.slug,
    name: benchmark.name,
    repository: benchmark.repository,
    pack: benchmark.pack,
    springBootVersion: benchmark.springBootVersion,
    readiness: benchmark.readiness ?? null,
    source: benchmark.source || 'catalog',
    validation: benchmark.validation || { status: 'not_requested', confidence: 0 },
    findings: {
      total: benchmark.findings?.length ?? 0,
      critical: benchmark.findings?.filter((finding) => finding.severity === 'critical').length ?? 0,
      warning: benchmark.findings?.filter((finding) => finding.severity === 'warning').length ?? 0,
      info: benchmark.findings?.filter((finding) => finding.severity === 'info').length ?? 0
    }
  })).sort(compareBenchmarks);
}

function normalizeReport(slug, report) {
  return {
    slug,
    name: report.project?.name || slug,
    repository: report.project?.source?.startsWith('https://github.com/')
      ? report.project.source
      : `https://github.com/${slug}`,
    pack: report.pack || 'unknown',
    springBootVersion: report.project?.springBootVersion || report.dependencies?.springBootVersion || 'unknown',
    readiness: report.readiness?.overall ?? null,
    source: report.benchmark?.source || 'catalog',
    validation: report.benchmark?.validation || { status: 'not_requested', confidence: 0 },
    findings: {
      total: report.findings?.length ?? 0,
      critical: report.readiness?.counts?.critical ?? 0,
      warning: report.readiness?.counts?.warning ?? 0,
      info: report.readiness?.counts?.info ?? 0
    }
  };
}

function compareBenchmarks(left, right) {
  if (left.pack !== right.pack) return left.pack.localeCompare(right.pack);
  return left.name.localeCompare(right.name);
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function normalizeHtml(html) {
  return html.replace(/[ \t]+$/gm, '');
}
