import fs from 'node:fs/promises';
import path from 'node:path';

const RELEASE_VERSION = 'v0.2.1';
const RELEASE_URL = `https://github.com/danielrna/enterprise-modernization-platform/releases/tag/${RELEASE_VERSION}`;
const SAMPLE_REPORT_URL = `https://github.com/danielrna/enterprise-modernization-platform/releases/download/${RELEASE_VERSION}/emp-smoke-report.zip`;
const DOCKER_IMAGE = `danielrna/enterprise-modernization-platform:${RELEASE_VERSION}`;
const GITHUB_ACTION = `danielrna/enterprise-modernization-platform@${RELEASE_VERSION}`;

export async function generateMigrationHub({ outDir, benchmarks = [], benchmarksDir = path.resolve(outDir, '..', 'benchmarks') }) {
  await fs.mkdir(outDir, { recursive: true });
  const benchmarkEvidence = await loadBenchmarkReports(benchmarksDir);
  const migrationBenchmarks = benchmarkEvidence.length ? benchmarkEvidence : normalizeBenchmarks(benchmarks);
  await fs.writeFile(path.join(outDir, 'index.html'), normalizeHtml(renderHubIndex(migrationBenchmarks)));
  await fs.writeFile(path.join(outDir, 'spring-boot-2-to-3.html'), normalizeHtml(renderMigrationPage(migrationBenchmarks)));
  for (const pack of packSummaries(migrationBenchmarks)) {
    await fs.writeFile(path.join(outDir, `${pack.id}.html`), normalizeHtml(renderPackEvidencePage(pack, migrationBenchmarks)));
  }
}

export async function generateBenchmarkIndex({ outDir, reports }) {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'index.html'), normalizeHtml(renderBenchmarkIndex(reports)));
}

function renderHubIndex(benchmarks) {
  const packTiles = packSummaries(benchmarks).map((pack) => `
      <a class="tile" href="${escapeHtml(pack.id)}.html"><strong>${escapeHtml(pack.name)}</strong><span>${escapeHtml(pack.count)} reports, ${escapeHtml(pack.checkout)} checkout-backed, ${escapeHtml(pack.passed)} passing validation.</span></a>`).join('');
  const rows = benchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.pack)}</td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${renderReadinessBadge(benchmark.readiness)}</td><td>${renderStatusBadge(benchmark.source, 'source')}</td><td>${renderStatusBadge(benchmark.validation.status)}</td></tr>`).join('');
  return page('Migration Hub', `
    ${nav('../')}
    <section>
      <h1>Migration Hub</h1>
      <p>Guides, reports, examples, and benchmark evidence for mandatory enterprise modernization work.</p>
    </section>
    <section class="layout">
      <a class="tile" href="spring-boot-2-to-3.html"><strong>Spring Boot 2 to 3</strong><span>Readiness guide, risks, report shape, and benchmark catalog.</span></a>
      <a class="tile" href="../benchmarks/index.html"><strong>Benchmark Reports</strong><span>${benchmarks.length} public benchmark reports generated by the CLI.</span></a>
      <a class="tile" href="../editions.html"><strong>Editions</strong><span>Community, Professional, Consultant, and Organization options.</span></a>
      <a class="tile" href="../contact.html"><strong>Contact</strong><span>Request Professional, Consultant, or Organization access.</span></a>
    </section>
    <h2>Pack Evidence Hubs</h2>
    <section class="layout">${packTiles}</section>
    <h2>Benchmark Set</h2>
    <div class="table-scroll"><table><thead><tr><th>Project</th><th>Repository</th><th>Pack</th><th>Spring Boot</th><th>Readiness</th><th>Source</th><th>Validation</th></tr></thead><tbody>${rows}</tbody></table></div>
  `);
}

function renderPackEvidencePage(pack, benchmarks) {
  const packBenchmarks = benchmarks.filter((benchmark) => benchmark.pack === pack.id);
  const validated = packBenchmarks.filter((benchmark) => benchmark.validation?.status === 'passed');
  const rows = packBenchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${renderReadinessBadge(benchmark.readiness)}</td><td>${escapeHtml(benchmark.findings.total)}</td><td>${renderStatusBadge(benchmark.source, 'source')}</td><td>${renderStatusBadge(benchmark.validation.status)}</td><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/report.json">JSON</a></td></tr>`).join('');
  const validatedCards = validated.length ? `<section class="validated">${validated.map((benchmark) => `
      <div class="proof-card">
        <strong><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></strong>
        <span>${escapeHtml(shortRepository(benchmark.repository))}</span>
        <div class="mini-metrics">
          <small>${escapeHtml(formatReadiness(benchmark.readiness))} readiness</small>
          <small>${escapeHtml(benchmark.validation.confidence || 0)}% confidence</small>
        </div>
      </div>`).join('')}</section>` : '<p>No reports for this pack currently have passing compile/test validation evidence.</p>';

  return page(`${pack.name} Evidence Hub`, `
    ${nav('../')}
    <section>
      <h1>${escapeHtml(pack.name)} Evidence Hub</h1>
      <p>Pack-specific benchmark evidence for ${escapeHtml(pack.name)}. Use this page to compare catalog-backed reports, checkout-backed reports, and validation outcomes.</p>
    </section>
    <section class="summary-row">
      <div><strong>${escapeHtml(pack.count)}</strong><span>Total reports</span></div>
      <div><strong>${escapeHtml(pack.checkout)}</strong><span>Checkout-backed</span></div>
      <div><strong>${escapeHtml(pack.passed)}</strong><span>Validation passed</span></div>
      <div><strong>${escapeHtml(pack.failed)}</strong><span>Validation failed</span></div>
    </section>
    <h2>Validated Evidence</h2>
    ${validatedCards}
    <h2>Pack Benchmark Reports</h2>
    <div class="table-scroll"><table><thead><tr><th>Project</th><th>Repository</th><th>Readiness</th><th>Findings</th><th>Source</th><th>Validation</th><th>Data</th></tr></thead><tbody>${rows}</tbody></table></div>
  `);
}

function packSummaries(benchmarks) {
  const packs = new Map();
  for (const benchmark of benchmarks) {
    const current = packs.get(benchmark.pack) || {
      id: benchmark.pack,
      name: packName(benchmark.pack),
      count: 0,
      checkout: 0,
      passed: 0,
      failed: 0
    };
    current.count += 1;
    if (benchmark.source === 'checkout') current.checkout += 1;
    if (benchmark.validation?.status === 'passed') current.passed += 1;
    if (benchmark.validation?.status === 'failed') current.failed += 1;
    packs.set(benchmark.pack, current);
  }
  return [...packs.values()].sort((left, right) => left.name.localeCompare(right.name));
}

function packName(pack) {
  const names = {
    'hibernate-readiness': 'Hibernate Readiness',
    'jakarta-readiness': 'Jakarta Readiness',
    'java-17-to-21-readiness': 'Java 17 to 21 Readiness',
    'junit-5-readiness': 'JUnit 5 Readiness',
    'spring-boot-3-readiness': 'Spring Boot 3 Readiness',
    'spring-security-6-readiness': 'Spring Security 6 Readiness'
  };
  return names[pack] || pack;
}

function renderMigrationPage(benchmarks) {
  const springBootBenchmarks = benchmarks.filter((benchmark) => benchmark.pack === 'spring-boot-3-readiness');
  const validatedBenchmarks = springBootBenchmarks.filter((benchmark) => benchmark.validation?.status === 'passed');
  const validatedBlock = renderValidatedBenchmarks(validatedBenchmarks);
  const benchmarkRows = springBootBenchmarks.map((benchmark) => `<tr><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(shortRepository(benchmark.repository))}</a></td><td>${escapeHtml(benchmark.springBootVersion)}</td><td>${renderReadinessBadge(benchmark.readiness)}</td><td>${escapeHtml(benchmark.findings.total)}</td><td>${renderStatusBadge(benchmark.source, 'source')}</td><td>${renderStatusBadge(benchmark.validation.status)}</td><td><a href="../benchmarks/${escapeHtml(benchmark.slug)}/report.json">JSON</a></td></tr>`).join('');

  return page('Spring Boot 2 to 3 Migration', `
    ${nav('../')}
    <section>
      <h1>Spring Boot 2 to 3 Migration</h1>
      <p>Readiness evidence for teams preparing the mandatory move from Spring Boot 2.x to Spring Boot 3.x.</p>
    </section>

    <section class="cta-band">
      <div>
        <strong>Start with a static readiness report.</strong>
        <span>Use the Docker command or GitHub Action, then share HTML and JSON evidence with no backend.</span>
      </div>
      <div class="actions">
        <a class="primary" href="#try-in-5-minutes">Run in 5 minutes</a>
        <a href="${SAMPLE_REPORT_URL}">Download sample report</a>
        <a href="${RELEASE_URL}">Release ${RELEASE_VERSION}</a>
      </div>
    </section>

    ${validatedBlock}

    <h2>Trust Evidence</h2>
    <section class="trust-grid">
      <div><strong>Checkout-backed</strong><span>The report was generated from a real cloned repository, not from catalog metadata.</span></div>
      <div><strong>Compilation passed</strong><span>The project compiled in the validation environment before the report was published.</span></div>
      <div><strong>Tests passed</strong><span>The test suite completed successfully, giving migration planning a stronger evidence baseline.</span></div>
      <div><strong>Confidence 95%</strong><span>Confidence is raised when both compile and test validation pass on the checkout.</span></div>
      <div><strong>Static report</strong><span>The HTML and JSON evidence can be shared with a client without a hosted backend.</span></div>
    </section>

    <h2>Consultant Workflow</h2>
    <section class="steps">
      <div><strong>1. Run</strong><span>Execute the free readiness report on the client repository.</span></div>
      <div><strong>2. Send report</strong><span>Share the static HTML report as neutral migration evidence.</span></div>
      <div><strong>3. Fix risks</strong><span>Prioritize Jakarta, build metadata, injection patterns, and client rules.</span></div>
      <div><strong>4. Validate</strong><span>Capture compile and test evidence before proposing migration execution.</span></div>
      <div><strong>5. Sell confidence</strong><span>Position the work as risk reduction, not as a generic code migration.</span></div>
    </section>

    <h2>What You Can Promise a Client</h2>
    <section class="promise">
      <div><strong>Readiness score</strong><span>A clear percentage and category scores for planning.</span></div>
      <div><strong>Version evidence</strong><span>Detected Spring Boot, Java, and build metadata.</span></div>
      <div><strong>Risk inventory</strong><span>Jakarta, static source findings, and repeated risk patterns.</span></div>
      <div><strong>Validation evidence</strong><span>Compile and test status when a checkout can be validated.</span></div>
      <div><strong>Client-owned rules</strong><span>Optional .preflight-rules.yml checks for internal standards.</span></div>
      <div><strong>Shareable report</strong><span>Static HTML and JSON outputs, no backend required.</span></div>
    </section>

    <h2>Free vs Professional</h2>
    <div class="table-scroll"><table>
      <thead><tr><th>Edition</th><th>Best For</th><th>Includes</th></tr></thead>
      <tbody>
        <tr><td>Community</td><td>First client conversation</td><td>Readiness analysis, HTML report, JSON report, public benchmark reference.</td></tr>
        <tr><td>Professional</td><td>Paid migration preparation</td><td>Validation evidence, Trust Engine report, repeatable benchmark pack, stronger confidence trail.</td></tr>
        <tr><td>Consultant</td><td>Repeated client work</td><td>Unlimited client usage, enterprise rules workflow, reusable reporting assets.</td></tr>
      </tbody>
    </table></div>

    <h2>Start With the Free Report</h2>
    <section class="actions">
      <a href="#try-in-5-minutes">Run the free readiness report</a>
      <a href="../benchmarks/gs-spring-boot-27/index.html">Use the validated benchmark as reference</a>
      <a href="../editions.html">Compare editions</a>
      <a href="../contact.html">Request access</a>
      <a href="${RELEASE_URL}">Download ${RELEASE_VERSION}</a>
    </section>

    <h2 id="try-in-5-minutes">Try in 5 Minutes</h2>
    <p>Run a readiness report on any Java or Spring repository. The output is a static HTML report and a machine-readable JSON report.</p>
    <pre><code>docker run --rm -v "$PWD:/workspace" ${DOCKER_IMAGE} analyze . --pack spring-boot-3-readiness --out reports/spring-boot-readiness</code></pre>
    <p>Open the generated report:</p>
    <pre><code>reports/spring-boot-readiness/index.html</code></pre>

    <h2>GitHub Action</h2>
    <pre><code>name: Spring Boot Readiness

on:
  workflow_dispatch:
  pull_request:

jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run readiness analysis
        uses: ${GITHUB_ACTION}
        with:
          path: .
          pack: spring-boot-3-readiness
          out: emp-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: emp-readiness-report
          path: emp-report</code></pre>

    <h2>Guide</h2>
    <p>This guide focuses on readiness evidence: build metadata, Spring Boot version detection, Jakarta namespace risk, static source findings, and an HTML report that can be shared without a backend.</p>

    <h2>Readiness Signals</h2>
    <ul>
      <li>Explicit Maven or Gradle build metadata</li>
      <li>Spring Boot version discovery</li>
      <li>javax to jakarta migration risk</li>
      <li>Dependency injection and legacy API cleanup findings</li>
      <li>OpenRewrite dry-run readiness for the transformation flow</li>
    </ul>

    <h2>Risk Matrix</h2>
    <div class="table-scroll"><table>
      <thead><tr><th>Risk</th><th>Why It Matters</th><th>Evidence Produced</th></tr></thead>
      <tbody>
        <tr><td>Jakarta namespace</td><td>Spring Boot 3 requires Jakarta EE APIs instead of Java EE packages.</td><td>javax usage findings, package-level risk, migration recommendation.</td></tr>
        <tr><td>Spring Boot version drift</td><td>Unknown or unsupported build metadata makes migration scope hard to estimate.</td><td>Maven or Gradle detection, Spring Boot version, applicability status.</td></tr>
        <tr><td>Dependency injection patterns</td><td>Field injection and legacy patterns often surface during framework upgrades.</td><td>Static findings separated by production and test sources.</td></tr>
        <tr><td>Build and test confidence</td><td>A migration is not credible without repeatable validation evidence.</td><td>Compile, test, rollback, and confidence sections when transform validation runs.</td></tr>
        <tr><td>Enterprise rules</td><td>Each organization has internal modernization rules beyond generic framework checks.</td><td>.preflight-rules.yml violations included in scoring and reports.</td></tr>
      </tbody>
    </table></div>

    <h2>Benchmark Reports</h2>
    <p>These public benchmark reports are checked into the repository and can be served directly from GitHub Pages. Source shows whether a report came from deterministic catalog metadata or a real repository checkout.</p>
    <div class="table-scroll"><table><thead><tr><th>Project</th><th>Repository</th><th>Detected Spring Boot</th><th>Readiness</th><th>Findings</th><th>Source</th><th>Validation</th><th>Data</th></tr></thead><tbody>${benchmarkRows}</tbody></table></div>

    <h2>What This Does Not Do</h2>
    <ul>
      <li>It does not run a hosted SaaS backend.</li>
      <li>It does not parse Java with a custom compiler or AST.</li>
      <li>It does not replace project-specific migration review.</li>
      <li>It does not apply changes during readiness analysis.</li>
    </ul>

    <h2>FAQ</h2>
    <p><strong>Does readiness analysis apply migrations?</strong> No. It measures readiness and creates evidence. Apply, rollback, compile, and test validation are part of the transformation flow.</p>
    <p><strong>Can this run in CI?</strong> Yes. Use the Docker image directly or the GitHub Action. The output directory can be uploaded as a build artifact.</p>
    <p><strong>Does it require a server?</strong> No. Reports, benchmark pages, and this hub are static files.</p>
  `);
}

function renderValidatedBenchmarks(benchmarks) {
  if (!benchmarks.length) return '';
  const realApplicationCount = benchmarks.filter((benchmark) => !shortRepository(benchmark.repository).startsWith('spring-guides/')).length;
  const realApplicationText = realApplicationCount
    ? `, including ${realApplicationCount} real application${realApplicationCount === 1 ? '' : 's'} outside Spring Guides`
    : '';
  const cards = benchmarks.map((benchmark) => `
      <div class="proof-card">
        <strong><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></strong>
        <span>${escapeHtml(shortRepository(benchmark.repository))}</span>
        <div class="mini-metrics">
          <small>${escapeHtml(benchmark.springBootVersion)} Spring Boot</small>
          <small>${escapeHtml(formatReadiness(benchmark.readiness))} readiness</small>
          <small>${escapeHtml(benchmark.validation.confidence)}% confidence</small>
        </div>
      </div>`).join('');
  return `
    <h2>Validated Benchmarks</h2>
    <section class="proof">
      <div>
        <strong>${escapeHtml(benchmarks.length)} checkout-backed benchmark${benchmarks.length === 1 ? '' : 's'} passed compile and test validation${escapeHtml(realApplicationText)}.</strong>
        <p>Each green benchmark is generated from a real repository checkout with captured compilation and test evidence.</p>
      </div>
      <div class="metrics">
        <span><strong>${escapeHtml(benchmarks.length)}</strong><small>Validated</small></span>
        <span><strong>${escapeHtml(realApplicationCount)}</strong><small>Real apps</small></span>
        <span><strong>passed</strong><small>Compile + tests</small></span>
        <span><strong>${escapeHtml(Math.round(benchmarks.reduce((sum, item) => sum + Number(item.validation.confidence || 0), 0) / benchmarks.length))}%</strong><small>Avg confidence</small></span>
      </div>
    </section>
    <section class="validated">${cards}</section>
  `;
}

function renderBenchmarkIndex(reports) {
  const summary = summarizeBenchmarkIndex(reports);
  const rows = reports.map((report) => {
    const validation = report.validation?.status || 'not_requested';
    const source = report.source || 'catalog';
    return `<tr data-benchmark-row data-source="${escapeHtml(source)}" data-validation="${escapeHtml(validation)}" data-search="${escapeHtml(`${report.name} ${shortRepository(report.repository)} ${report.pack || ''} ${report.springBootVersion || ''}`.toLowerCase())}"><td><a href="${escapeHtml(report.slug)}/index.html">${escapeHtml(report.name)}</a><div class="subtle">${escapeHtml(shortRepository(report.repository))}</div></td><td>${renderReadinessBadge(report.readiness)}</td><td>${renderStatusBadge(source, 'source')}</td><td>${renderStatusBadge(validation)}</td><td><a href="${escapeHtml(report.repository)}">${escapeHtml(shortRepository(report.repository))}</a></td></tr>`;
  }).join('');
  return page('Benchmark Reports', `
    ${nav('../')}
    <section>
      <h1>Benchmark Reports</h1>
      <p>Public readiness evidence generated from catalog metadata and real repository checkouts.</p>
    </section>
    <section class="summary-row">
      <div><strong>${reports.length}</strong><span>Total reports</span></div>
      <div><strong>${summary.checkout}</strong><span>Checkout-backed</span></div>
      <div><strong>${summary.passed}</strong><span>Validation passed</span></div>
      <div><strong>${summary.ready}</strong><span>80%+ readiness</span></div>
    </section>
    <section class="filters" aria-label="Benchmark filters">
      <input id="benchmark-search" type="search" placeholder="Search project, repository, pack, or version">
      <select id="source-filter" aria-label="Filter by source">
        <option value="all">All sources</option>
        <option value="checkout">Checkout-backed</option>
        <option value="catalog">Catalog</option>
      </select>
      <select id="validation-filter" aria-label="Filter by validation status">
        <option value="all">All validation states</option>
        <option value="passed">Passed</option>
        <option value="failed">Failed</option>
        <option value="skipped">Skipped</option>
        <option value="not_requested">Not requested</option>
      </select>
      <span id="benchmark-count">${reports.length} shown</span>
    </section>
    <div class="table-scroll"><table><thead><tr><th>Project</th><th>Readiness</th><th>Source</th><th>Validation</th><th>Repository</th></tr></thead><tbody>${rows}</tbody></table></div>
  `, benchmarkFilterScript());
}

function formatReadiness(readiness) {
  return readiness === null ? 'N/A' : `${readiness}%`;
}

function renderReadinessBadge(readiness) {
  if (readiness === null || readiness === undefined) return '<span class="badge neutral">N/A</span>';
  const value = Number(readiness);
  const tone = value >= 80 ? 'good' : value >= 65 ? 'warn' : 'bad';
  return `<span class="badge ${tone}">${escapeHtml(value)}%</span>`;
}

function renderStatusBadge(status, kind = 'validation') {
  const value = String(status || 'not_requested');
  const tone = statusTone(value, kind);
  return `<span class="badge ${tone}">${escapeHtml(formatStatus(value))}</span>`;
}

function statusTone(status, kind) {
  if (kind === 'source') return status === 'checkout' ? 'good' : 'neutral';
  if (status === 'passed') return 'good';
  if (status === 'failed') return 'bad';
  if (status === 'skipped' || status === 'not_requested') return 'neutral';
  return 'warn';
}

function formatStatus(status) {
  return status.replaceAll('_', ' ');
}

function summarizeBenchmarkIndex(reports) {
  return {
    checkout: reports.filter((report) => (report.source || 'catalog') === 'checkout').length,
    passed: reports.filter((report) => report.validation?.status === 'passed').length,
    ready: reports.filter((report) => Number(report.readiness) >= 80).length
  };
}

function nav(prefix = '') {
  return `<nav class="site-nav">
      <a href="${prefix}index.html">Home</a>
      <a href="${prefix}migration-hub/spring-boot-2-to-3.html">Migration Hub</a>
      <a href="${prefix}benchmarks/index.html">Benchmarks</a>
      <a href="${prefix}packs/index.html">Packs</a>
      <a href="${prefix}release-notes/index.html">Release Notes</a>
      <a href="${prefix}editions.html">Editions</a>
      <a href="${prefix}contact.html">Contact</a>
    </nav>`;
}

function benchmarkFilterScript() {
  return `<script>
  const rows = Array.from(document.querySelectorAll('[data-benchmark-row]'));
  const search = document.querySelector('#benchmark-search');
  const source = document.querySelector('#source-filter');
  const validation = document.querySelector('#validation-filter');
  const count = document.querySelector('#benchmark-count');
  function applyBenchmarkFilters() {
    const query = search.value.trim().toLowerCase();
    const selectedSource = source.value;
    const selectedValidation = validation.value;
    let shown = 0;
    for (const row of rows) {
      const matchesQuery = !query || row.dataset.search.includes(query);
      const matchesSource = selectedSource === 'all' || row.dataset.source === selectedSource;
      const matchesValidation = selectedValidation === 'all' || row.dataset.validation === selectedValidation;
      const visible = matchesQuery && matchesSource && matchesValidation;
      row.hidden = !visible;
      if (visible) shown += 1;
    }
    count.textContent = shown + ' shown';
  }
  for (const control of [search, source, validation]) control.addEventListener('input', applyBenchmarkFilters);
</script>`;
}

function page(title, body, script = '') {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --ink:#17202a; --muted:#64748b; --line:#d8dee8; --bg:#f7f9fb; --panel:#fff; --accent:#1769aa; --accent-dark:#0f4f84; --ok:#217a45; --warn:#966600; --bad:#b42318; }
    * { box-sizing:border-box; }
    body { margin:0; font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; color:var(--ink); background:var(--bg); }
    main { max-width:1080px; margin:0 auto; padding:32px 24px; }
    h1 { margin:0 0 8px; font-size:34px; letter-spacing:0; }
    h2 { margin:28px 0 10px; font-size:21px; letter-spacing:0; }
    p { max-width:760px; color:var(--muted); }
    a { color:var(--accent); text-decoration:none; }
    a:hover { text-decoration:underline; }
    .site-nav { display:flex; flex-wrap:wrap; gap:10px 14px; align-items:center; margin:0 0 28px; padding-bottom:16px; border-bottom:1px solid var(--line); }
    .site-nav a { color:var(--muted); font-size:14px; }
    .site-nav a:first-child { color:var(--ink); font-weight:700; }
    .layout { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:14px; margin:24px 0; }
    .tile { display:flex; flex-direction:column; gap:6px; min-height:118px; padding:18px; background:var(--panel); border:1px solid var(--line); border-radius:8px; color:var(--ink); }
    .tile span { color:var(--muted); }
    .cta-band { display:grid; grid-template-columns:minmax(0, 1fr) auto; gap:18px; align-items:center; margin:24px 0; padding:18px; background:#eef6fd; border:1px solid #bfd7ee; border-left:4px solid var(--accent); border-radius:8px; }
    .cta-band div:first-child { display:flex; flex-direction:column; gap:4px; }
    .cta-band span,.subtle { color:var(--muted); }
    .summary-row { display:grid; grid-template-columns:repeat(4, minmax(0, 1fr)); gap:12px; margin:24px 0; }
    .summary-row div { display:flex; flex-direction:column; gap:3px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .summary-row strong { font-size:24px; }
    .summary-row span { color:var(--muted); }
    .filters { display:grid; grid-template-columns:minmax(240px, 1fr) 170px 190px auto; gap:10px; align-items:center; margin:18px 0 14px; }
    input,select { width:100%; min-height:40px; padding:8px 10px; border:1px solid var(--line); border-radius:6px; background:var(--panel); color:var(--ink); font:inherit; }
    .proof { display:grid; grid-template-columns:minmax(0, 1fr) auto; gap:18px; align-items:center; padding:18px; background:var(--panel); border:1px solid var(--line); border-left:4px solid #217a45; border-radius:8px; }
    .proof p { margin:6px 0 0; }
    .metrics { display:grid; grid-template-columns:repeat(4, minmax(92px, 1fr)); gap:10px; }
    .metrics span { display:flex; flex-direction:column; gap:2px; padding:10px 12px; background:#f8fafc; border:1px solid var(--line); border-radius:6px; }
    .metrics small { color:var(--muted); font-size:12px; }
    .validated { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:10px; margin:12px 0 24px; }
    .proof-card { display:flex; flex-direction:column; gap:6px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .proof-card span,.mini-metrics small { color:var(--muted); }
    .mini-metrics { display:flex; flex-wrap:wrap; gap:8px; }
    .trust-grid { display:grid; grid-template-columns:repeat(5, minmax(0, 1fr)); gap:10px; }
    .trust-grid div { display:flex; flex-direction:column; gap:5px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .trust-grid span { color:var(--muted); }
    .steps { display:grid; grid-template-columns:repeat(5, minmax(0, 1fr)); gap:10px; }
    .steps div,.promise div { display:flex; flex-direction:column; gap:5px; padding:14px; background:var(--panel); border:1px solid var(--line); border-radius:8px; }
    .steps span,.promise span { color:var(--muted); }
    .promise { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:10px; }
    .actions { display:flex; flex-wrap:wrap; gap:10px; }
    .actions a { display:inline-flex; align-items:center; min-height:40px; padding:8px 12px; background:var(--panel); border:1px solid var(--line); border-radius:6px; }
    .actions a.primary { background:var(--accent); color:#fff; border-color:var(--accent-dark); font-weight:700; }
    pre { overflow:auto; padding:14px; background:#111827; color:#f8fafc; border-radius:8px; }
    code { font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
    .table-scroll { width:100%; overflow-x:auto; border-radius:8px; }
    table { width:100%; border-collapse:collapse; background:var(--panel); border:1px solid var(--line); border-radius:8px; overflow:hidden; }
    th,td { text-align:left; padding:10px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
    th { font-size:12px; color:var(--muted); text-transform:uppercase; }
    td { overflow-wrap:anywhere; }
    .badge { display:inline-flex; align-items:center; justify-content:center; min-width:72px; min-height:24px; padding:3px 8px; border-radius:999px; font-size:12px; font-weight:700; text-transform:capitalize; }
    .badge.good { background:#dff7e8; color:var(--ok); }
    .badge.warn { background:#fff3c4; color:var(--warn); }
    .badge.bad { background:#ffe4e0; color:var(--bad); }
    .badge.neutral { background:#eef2f7; color:#344054; }
    li { margin:6px 0; }
    @media (max-width: 900px) { .steps,.promise,.validated,.trust-grid,.summary-row { grid-template-columns:1fr 1fr; } .cta-band,.filters { grid-template-columns:1fr; } }
    @media (max-width: 720px) { main { padding:24px 16px; } .layout,.proof,.steps,.promise,.validated,.trust-grid,.summary-row { grid-template-columns:1fr; } .metrics { grid-template-columns:1fr; } h1 { font-size:27px; } table { min-width:720px; } }
  </style>
</head>
<body><main>${body}</main>${script}</body>
</html>
`;
}

function shortRepository(repository) {
  return repository.replace('https://github.com/', '');
}

async function loadBenchmarkReports(benchmarksDir) {
  const entries = await fs.readdir(benchmarksDir, { withFileTypes: true }).catch(() => []);
  const reports = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const slug = entry.name;
    const reportPath = path.join(benchmarksDir, slug, 'report.json');
    const report = await readJson(reportPath);
    if (!report) continue;
    reports.push(normalizeReport(slug, report));
  }
  return reports.sort(compareBenchmarks);
}

async function readJson(file) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch {
    return null;
  }
}

function normalizeBenchmarks(benchmarks) {
  return benchmarks.map((benchmark) => ({
    slug: benchmark.slug,
    name: benchmark.name,
    repository: benchmark.repository,
    pack: benchmark.pack,
    springBootVersion: benchmark.springBootVersion,
    readiness: benchmark.readiness ?? null,
    source: benchmark.source || 'catalog',
    validation: benchmark.validation || { status: 'not_requested', confidence: 0 },
    findings: {
      total: benchmark.findings?.length ?? 0,
      critical: benchmark.findings?.filter((finding) => finding.severity === 'critical').length ?? 0,
      warning: benchmark.findings?.filter((finding) => finding.severity === 'warning').length ?? 0,
      info: benchmark.findings?.filter((finding) => finding.severity === 'info').length ?? 0
    }
  })).sort(compareBenchmarks);
}

function normalizeReport(slug, report) {
  return {
    slug,
    name: report.project?.name || slug,
    repository: report.project?.source?.startsWith('https://github.com/')
      ? report.project.source
      : `https://github.com/${slug}`,
    pack: report.pack || 'unknown',
    springBootVersion: report.project?.springBootVersion || report.dependencies?.springBootVersion || 'unknown',
    readiness: report.readiness?.overall ?? null,
    source: report.benchmark?.source || 'catalog',
    validation: report.benchmark?.validation || { status: 'not_requested', confidence: 0 },
    findings: {
      total: report.findings?.length ?? 0,
      critical: report.readiness?.counts?.critical ?? 0,
      warning: report.readiness?.counts?.warning ?? 0,
      info: report.readiness?.counts?.info ?? 0
    }
  };
}

function compareBenchmarks(left, right) {
  if (left.pack !== right.pack) return left.pack.localeCompare(right.pack);
  return left.name.localeCompare(right.name);
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function normalizeHtml(html) {
  return html.replace(/[ \t]+$/gm, '');
}
